//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trello.Data.DbTrello.Data.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoTrelloEntities : DbContext
    {
        public proyectoTrelloEntities()
            : base("name=proyectoTrelloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<proyecto> proyecto { get; set; }
        public virtual DbSet<ProyectoUsuario> ProyectoUsuario { get; set; }
        public virtual DbSet<requisitos> requisitos { get; set; }
        public virtual DbSet<RequisitosEstado> RequisitosEstado { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<sprint> sprint { get; set; }
        public virtual DbSet<trabajo> trabajo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
