//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trello.Data.DbTrello.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoUsuario
    {
        public int idUsuario { get; set; }
        public int idRol { get; set; }
        public int idProyecto { get; set; }
    
        public virtual proyecto proyecto { get; set; }
        public virtual rol rol { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
