//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trello.Data.DbTrello.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisitos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requisitos()
        {
            this.requisitos1 = new HashSet<requisitos>();
            this.trabajo = new HashSet<trabajo>();
            this.sprint = new HashSet<sprint>();
        }
    
        public int idRequisitos { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public short Prioridad { get; set; }
        public short Puntos { get; set; }
        public short Estado { get; set; }
        public int idInformador { get; set; }
        public Nullable<int> idResponsable { get; set; }
        public int idProyecto { get; set; }
        public Nullable<int> idRequisitosPadre { get; set; }
        public Nullable<System.DateTime> TiempoEstimado { get; set; }
        public Nullable<System.DateTime> fechacreado { get; set; }
    
        public virtual proyecto proyecto { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requisitos> requisitos1 { get; set; }
        public virtual requisitos requisitos2 { get; set; }
        public virtual usuario usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajo> trabajo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sprint> sprint { get; set; }
    }
}
