//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trello.Data.DbTrello.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sprint()
        {
            this.requisitos = new HashSet<requisitos>();
        }
    
        public int idSprint { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaIncio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<short> Estados { get; set; }
        public int idProyecto { get; set; }
    
        public virtual proyecto proyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requisitos> requisitos { get; set; }
    }
}
